# Generated by Django 5.0 on 2024-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('DOCID', models.AutoField(primary_key=True, serialize=False)),
                ('DocName', models.CharField(max_length=255)),
                ('DocType', models.CharField(blank=True, max_length=50)),
                ('DocExtn', models.CharField(blank=True, max_length=10, null=True)),
                ('DocLang', models.CharField(blank=True, max_length=50, null=True)),
                ('DocPath', models.CharField(max_length=255)),
                ('UploadData', models.DateTimeField(auto_now_add=True)),
                ('LastAccessed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
