# Generated by Django 5.0 on 2024-01-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTools',
            fields=[
                ('ToolID', models.AutoField(primary_key=True, serialize=False)),
                ('ToolName', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='DOCID',
            new_name='DocID',
        ),
        migrations.CreateModel(
            name='ToolsUsage',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('Os', models.CharField(max_length=100)),
                ('Input_Path', models.CharField(max_length=255)),
                ('Output_Path', models.CharField(max_length=255)),
                ('DocID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.documents')),
                ('ToolID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.mastertools')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.newusers')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('ExecutionTime', models.IntegerField()),
                ('Location', models.CharField(max_length=255)),
                ('Status', models.BooleanField(default=False)),
                ('Comments', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.newusers')),
                ('TaskID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.toolsusage')),
            ],
        ),
    ]
